@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ListOrderCommandParser" as ListOrderCommandParser LOGIC_COLOR
participant "l:ListOrderCommand" as ListOrderCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box



[-> LogicManager : execute(args)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(args)
activate AddressBookParser

create ListOrderCommandParser
AddressBookParser -> ListOrderCommandParser
activate ListOrderCommandParser

ListOrderCommandParser --> AddressBookParser
deactivate ListOrderCommandParser

AddressBookParser -> ListOrderCommandParser : parse(args)
activate ListOrderCommandParser


create ListOrderCommand
ListOrderCommandParser -> ListOrderCommand :
activate ListOrderCommand

ListOrderCommand --> ListOrderCommandParser :
deactivate ListOrderCommand

ListOrderCommandParser --> AddressBookParser : l
deactivate ListOrderCommandParser
ListOrderCommandParser -[hidden]-> AddressBookParser
destroy ListOrderCommandParser

AddressBookParser --> LogicManager : l
deactivate AddressBookParser

LogicManager -> ListOrderCommand : execute(m)
activate ListOrderCommand

ListOrderCommand -> Model : getFilteredPersonList()
activate Model

Model --> ListOrderCommand : lastShownList
deactivate Model

ListOrderCommand -> Model : getSortedOrder(person)
activate Model

Model --> ListOrderCommand : sortedOrders
deactivate Model

ListOrderCommand -> ListOrderCommand : createOrderListString(sortedOrders)
activate ListOrderCommand
ListOrderCommand --> ListOrderCommand :
deactivate ListOrderCommand

create CommandResult
ListOrderCommand -> CommandResult :
activate CommandResult
CommandResult --> ListOrderCommand
deactivate CommandResult

ListOrderCommand --> LogicManager : r
deactivate ListOrderCommand

[<-- LogicManager : r
deactivate LogicManager
@enduml
