@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ShowFavouriteCommandParser" as ShowFavouriteCommandParser LOGIC_COLOR
participant "a:ShowFavouriteCommand" as ShowFavouriteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box AddressBook BOOK_COLOR_T1
participant "filteredPersons:FilteredList" as FilteredList BOOK_COLOR
end box


[-> LogicManager : execute(args)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(args)
activate AddressBookParser

create ShowFavouriteCommandParser
AddressBookParser -> ShowFavouriteCommandParser
activate ShowFavouriteCommandParser

ShowFavouriteCommandParser --> AddressBookParser
deactivate ShowFavouriteCommandParser

AddressBookParser -> ShowFavouriteCommandParser : parse(args)
activate ShowFavouriteCommandParser

create ShowFavouriteCommand
ShowFavouriteCommandParser -> ShowFavouriteCommand
activate ShowFavouriteCommand

ShowFavouriteCommand --> ShowFavouriteCommandParser :
deactivate ShowFavouriteCommand

ShowFavouriteCommandParser --> AddressBookParser : a
deactivate ShowFavouriteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ShowFavouriteCommandParser -[hidden]-> AddressBookParser
destroy ShowFavouriteCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> ShowFavouriteCommand : execute(m)
activate ShowFavouriteCommand

ShowFavouriteCommand -> Model : updateFilteredPersonList(pred)
activate Model

Model -> FilteredList : setPredicate(pred)
FilteredList --> Model

Model --> ShowFavouriteCommand
deactivate Model

ShowFavouriteCommand -> CommandResult
activate CommandResult
CommandResult --> ShowFavouriteCommand
deactivate CommandResult

ShowFavouriteCommand --> LogicManager : r
deactivate ShowFavouriteCommand

[<-- LogicManager : r
deactivate LogicManager

@enduml
